# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: shinyapp:$(build.buildId)
  dockerId: dockerandresu13
  dockerPassword: a7Ha82v7tXi+ZWLfxT3ZuCEE19ffs82p

steps: 
- script: |
          docker build -f Dockerfile -t $(imageName) .
          docker tag $(imageName) dockerandresu13.azurecr.io/$(imageName)
          docker login -u dockerandresu13 -p a7Ha82v7tXi+ZWLfxT3ZuCEE19ffs82p dockerandresu13.azurecr.io
          docker push dockerandresu13.azurecr.io/$(imageName)
          
  displayName: 'docker build and push'
  env:
    pswd: $(dockerPassword)
    # docker build -f Dockerfile -t $(imageName) .
    # docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    # docker push $(imageName)
    
    # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface



